version: "3"

services:

  # With watchtower you can update the running version of your containerized app simply by pushing a new image to the
  # Docker Hub or your own image registry. Watchtower will pull down your new image, gracefully shut down your
  # existing container and restart it with the same options that were used when it was deployed initially.
  # https://hub.docker.com/r/containrrr/watchtower
  # https://github.com/containrrr/watchtower
  # https://containrrr.dev/watchtower/

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


  # A highly customizable homepage (or startpage /
  # application dashboard) with Docker and service
  # API integrations. 
  # https://github.com/benphelps/homepage
  # https://gethomepage.dev
  # https://gethomepage.dev/en/configs/docker/
  
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    ports:
      - 2375:2375
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
        - /home/autiboy/homepage/config:/app/config
    ports:
        - 3000:3000
    restart: unless-stopped
